Ankit-11525/e-commerce_redstore.github.io

- account.html
- allproducts.html
- cart.html
- index.html
- productdetail.html
> Updated copyright year to use js.

- style.css
This fixes issue #6 
I have fixed the alignment of the navigation links. Please review the code and your suggestions are welcome.
> Fixed nav-links' alignment

- account.html
- allproducts.html
- cart.html
- index.html
- productdetail.html
- style.css
Add Scroll Bar,
Add Animation On Scroll,
Add Some CSS,
Mobile Navbar CSS,
Add Favicon,
etc...
> Update All Files

- index.html
I have fixed the brands section on the website where I attached links with the logos. Now, when a user clicks on them it will redirect to the actual website of the brand.
Kindly review the code and your suggestions are welcome.
> Added brand website links in the brands section

- .github/workflows/main.yml
- README.md
> Added github actions to auto add contributors

- index.html
- style.css
Issue #20  
I have deployed it on GitHub pages https://aaheli8.github.io/e-commerce_redstore.github.io/.
The Changes that I have made.
1. Added a Zoom in hover style on the featured section images.
Whenever hovering is done on any of the images, it zooms in for a better view.
2.  Added a Testimonial heading and a CSS underline animation for enhancement.
> Issue #20 Enhancement of the featured Section and the Testimonial Section

- account.html
- allproducts.html
- cart.html
- index.html
- productdetail.html
- style.css
> Add Social media icons at footer on all pages

- cart.html
- productdetail.html
Hello! I have completed the solution for the allotted issue. I have used local storage to store the added items and then listed them in the cart page and also made the total section dynamic.
> solution for issue regarding addition of items to cart (#12)

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/workflows/main.yml
> add-gh-issue-templates

- style.css
I have fixed the issue raised.
> fix : fixed the cursor type on CTA's

- style.css
I update the header row margin [ margin-top : 0 ]
> header row margin top update

- style.css
improved header hover experience
> improved header 

- index.html
- style.css
Fixes issue #50 
Adds hover feature to the Latest and Feature products section which enhances user experience.
> Added hover feature to Latest and Feature products section

- allproducts.html
- index.html
- style.css
I have add transition and animation effect on hovering in **allproducts.html** (in **All Product** section) and in **index.html**(in **featured products** section and in **latest product** section). On hovering in product images transiton effect will be visible.Thank you @Ankit-11525 for assigning me this issue.I hope you will like it . Btw this is my first PR.
> add hover transition and animation effect in allProducts.html and index.html(latest products section and featured product section) 

- index.html
- style.css
- Added Image Animation
- Curved Edges Images
Video of the Changes Made.
[![Watch the video](https://i.imgur.com/vKb2F1B.png)](https://youtu.be/6Mwhgg3qX7U)
> Added Image Animation and CSS Edits.

- README.md
- account.html
- allproducts.html
- cart.html
- index.html
- productdetail.html
Added links to the "Download the app" and "Useful Links" section in the footer for all pages.
> Added Links to Footer

- index.html
- style.css
Reverts Ankit-11525/e-commerce_redstore.github.io#68
> Revert "Added Image Animation and CSS Edits."

- allproducts.html
- index.html
- style.css
Reverts Ankit-11525/e-commerce_redstore.github.io#65
> Revert "Revert "add hover transition and animation effect in allProducts.html and index.html(latest products section and featured product section) ""

- index.html
- style.css
Reverts Ankit-11525/e-commerce_redstore.github.io#61
> Revert "UI of the navbar has been enhanced"

- account.html
- style.css
Added custom styling on the Login/Register Card.
> Modified Login and Registration card UI

- allproducts.html
- index.html
- style.css
When you hover on products , Transition effect will be there.
This will give enhance look to the Website.
> Add transition and animation on hovering on product

- style.css
and added new functionality to it
> Now Scroll Bar is working fine

- about.html
- allproducts.html
- cart.html
- index.html
- productdetail.html
- style.css
Made a template for the About page and linked it to all the other pages.
> Made the About Page

- index.html
- style.css
social media icons are aligned properly in a line now.
> social media icon fixes

- index.html
- style.css
#92 solved.
Added scroll-up button functionality to the main page. Please review the PR and merge it. Also, let me know if there are any issues. Thanks.
> Added scroll-up button to index page

- account.html
- allproducts.html
- cart.html
- index.html
- productdetail.html
- style.css
I have added toggle button inside navbar in all the webpages. After clicking on toggle button you can change theme to dark and vice-versa.
before clicking on toggle button
After clicking on toggle button
> Added toggle button for changing theme.

- style.css
> mobile nav menu design improved

- index.html
* Fixes issue #96
* Made the changes mentioned in issue #96 
* Removed the random reviews generated by the computer and added proper and meaningful reviews for all the 3 customers in the testimonial section.
Before: 
After:
> Modified the testimonial section

- account.html
- allproducts.html
- index.html
- style.css
Changed hover / click style of footer images to pointer.
> added cursor style

- allproducts.html
The icons were misaligned in the footer, so made the change
> spacing of icons in the footer

- .vscode/settings.json
- index.html
- productdetail.html
- style.css
I have reduced the excessive hover effect on "Top Categories" section and on the products card. And, I have also added hover effect on "View More" button in productdetail.html page.
> Reducing hover effect

- style.css
Changed the Link colors for improved readability of User.
> Changed Footer Links UI

- allproducts.html
Extra characters and not needed "> was present at line number 14 which was making the look of product page uneven as compared to other pages.
> Not needed characters at the end of line 14

- cart.html
- productdetail.html
- style.css
- added Toast on Add to cart button on the ProductDetail page
- added Toast on Remove button on the Cart page
Note - there are a lot of additions and deletions shown as I had Prettier extension that formatted the indentation of the code.
---
> Added Toast on Add to cart and remove from cart

- index.html
- style.css
Previous there was some issue in the dark mode.
By making some changes I have made the offer section more joined
> Changes in dark mode

- style.css
> Added Box-Shadow

- style.css
> fix toggle ball position

- style.css
Reverts Ankit-11525/e-commerce_redstore.github.io#149
> Revert "Added Box-Shadow"

- style.css
this PR resolve issue #152 
Please add Hacktoberfest 2022 labels.
> fix margin for product image and info

- index.html
> Reduce reloading time

- account.html
- style.css
I added the left  to right color change hovering effect on the top most navigation bar i.e  on home , products , about , contact ,account.
**Description**
On hovering the mouse there would be right to left color changing hovering effect. Which makes the Nav bar  more Animated.
**Changed**
> Added left to right hovering effect 

- account.html
- style.css
Reverts Ankit-11525/e-commerce_redstore.github.io#174
> Revert "Added left to right hovering effect "

- account.html
- allproducts.html
- cart.html
- contact.html
Fix for #176 
- removed unwanted code
- improved code readability by formatting using Prettier
> Improve the code quality, Issue #176

- index.html
I have successfully commit my change where I have changed the icons of the socials in the footer.
I have a screenshot of my work below, consider it and merge it into the main repo
Before:
After:
> Made the icons rounded 

- index.html
I am excited to share to you that I have changed your website by giving my precious time to you.
Have fun !!!
> Added app links of play store and app store

- style.css
> Smooth transition in back to top button

- style.css
> smooth hover effect on icon 
